
services:
  postgres: 
    image: postgres:14.20
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "${POSTGRES_PORT}:5432"
    volumes:
      # See docs: https://hub.docker.com/_/postgres
      - postgres_data:/var/lib/postgresql/20/docker
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
    networks:
      - weather_network
  
  weather-script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_script_container
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./scripts:/app/scripts
      - ./outputs:/app/outputs
      - ./coordinates.json:/app/coordinates.json
    networks:
      - weather_network

volumes:
  - postgres_data

networks:
  - weather_network:
    driver: bridge





